theme: jekyll-theme-midnight
title: GitHub website page of whosyourdady3rm
description: Welcome to my page!
My alias is whosyourdady and I joined GitHub in 2020, starting using it in programming during the pandemic that took the world by storm in the year of 2020.
